blank_issues_enabled: false
contact_links:
  - name: Blossom AI issues
    url: https://github.com/stackblitz-labs/blossom-ai/issues/new/choose
    about: Report issues related to Blossom AI
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other Blossom AI users.
